import { PERMISSION, PermissionType } from "../enums/permission.enum";
import { RoleType } from "../enums/role.enum";

export const RolePermissions: Record<RoleType, Array<PermissionType>> = {
  // Admin role should have all permissions
  Admin: [
    // User Management
    PERMISSION.MANAGE_USERS,
    // Property Management
    PERMISSION.CREATE_PROPERTY,
    PERMISSION.READ_PROPERTY, // Added: Admins should be able to read properties
    PERMISSION.UPDATE_PROPERTY,
    PERMISSION.DELETE_PROPERTY,
    // Appointment Management
    PERMISSION.CREATE_APPOINTMENT, // Added: Admins might need to manage appointments
    PERMISSION.UPDATE_APPOINTMENT,
    PERMISSION.APPROVE_APPOINTMENT, // Added: Admins might need to manage appointments
    PERMISSION.DELETE_APPOINTMENT,
    PERMISSION.CREATE_REVIEW,
    PERMISSION.READ_REVIEW,
    PERMISSION.UPDATE_REVIEW,
    PERMISSION.DELETE_REVIEW,
    PERMISSION.CREATE_DEAL,
    PERMISSION.READ_DEAL,
    PERMISSION.MANAGE_DEALS,
    // General
    PERMISSION.VIEW_DASHBOARD, // Added: Admins should have access to dashboards
    // Amenity Management
    PERMISSION.MANAGE_AMENITIES,
  ],
  Agent: [
    PERMISSION.CREATE_PROPERTY,
    PERMISSION.READ_PROPERTY,
    PERMISSION.UPDATE_PROPERTY,
    PERMISSION.DELETE_PROPERTY,
    PERMISSION.CREATE_APPOINTMENT,
    PERMISSION.UPDATE_APPOINTMENT,
    PERMISSION.APPROVE_APPOINTMENT,
    PERMISSION.DELETE_APPOINTMENT,
    PERMISSION.CREATE_REVIEW,
    PERMISSION.READ_REVIEW,
    PERMISSION.UPDATE_REVIEW,
    PERMISSION.DELETE_REVIEW,
    PERMISSION.CREATE_DEAL,
    PERMISSION.READ_DEAL,
    PERMISSION.MANAGE_DEALS,
    PERMISSION.MANAGE_AMENITIES,
  ],
  User: [
    PERMISSION.READ_PROPERTY,
    PERMISSION.CREATE_APPOINTMENT,
    PERMISSION.UPDATE_APPOINTMENT,
    PERMISSION.DELETE_APPOINTMENT,
    PERMISSION.CREATE_REVIEW,
    PERMISSION.READ_REVIEW,
    PERMISSION.UPDATE_REVIEW,
    PERMISSION.DELETE_REVIEW,
  ],
};
